# Generated by Django 5.2.8 on 2025-11-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Megnevezés')),
                ('starting_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Induló ár (HUF)')),
                ('auction_time', models.DateTimeField(verbose_name='Árverés ideje')),
                ('category', models.CharField(choices=[('festmény', 'Festmény'), ('ékszer', 'Ékszer'), ('porcelán', 'Porcelán')], max_length=20, verbose_name='Kategória')),
            ],
        ),
    ]
