# Generated by Django 5.2.8 on 2025-12-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_item_current_price_item_is_active_item_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
